# Generated by Django 2.2 on 2022-03-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='absent_students',
        ),
        migrations.AddField(
            model_name='lesson',
            name='absent_students',
            field=models.ManyToManyField(to='university.Student'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
